<!-- Embed form -->
<script>
function closeEmbedCode() {
	document.getElementById("embedForm").style.display="none";
	location.href="";
}
</script>
<div id='embedForm' class='trnsdiv'>
	<div class='divForm' style="max-width: 600px; width: 100%;">
		<div class='caption'>Video embedding code</div>
		<div class="disch" style='line-height: 120%;'>
			<br/>
			To embed this video to your web page, paste the following code at the end of your html.<br/><br/>
			<pre id='embedCode' style='text-align: left;'>&nbsp;</pre>
		</div>
		<br/>
		<div style="line-height: 250%; background-color: white; text-align: center;">
			<p style='clear: both;'>
				 <span class='button' onClick="closeEmbedCode();">&nbsp;Close</span>&emsp;&emsp;
			</p>
		</div>
	</div><br/>
</div>
<!-- End of Embed form -->
