<div style='display: block; font-size: 0px;'>

<div class='footer1'>
<div class='col-4 col-m-12' style='padding: 0px; margin: 0px; font-size: 14px; text-align: left;'>
<h3>ABOUT US</h3>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</div>
<div class='col-4 col-m-12' style='padding: 0px; margin: 0px; font-size: 14px; text-align: left;'>
<h3>QUICK LINKS</h3>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</div>
<div class='col-4 col-m-12' style='padding: 0px; margin: 0px; font-size: 14px; text-align: left;'>
<h3>GET IN TOUCH</h3>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</div>
</div>
<div class='footer2'>
<div class='col-8 col-m-12' style='padding: 20px; margin: 0px; text-align: left; font-size: 12px;'>
&copy;CasterBuddy 2016 | All rights reserved
</div>
<div class='col-4 col-m-12' style='padding: 0px; margin: 0px;'>
<img src='images/social.png'>
</div>
<div style="clear: both;"></div>
</div>

</div>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="js/jquery.scrollTo.min.js"></script>
    <script src="js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="js/jquery.sparkline.js" type="text/javascript"></script>
    <script src="assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js"></script>
    <script src="js/owl.carousel.js" ></script>
    <script src="js/jquery.customSelect.min.js" ></script>
    <script src="js/respond.min.js" ></script>

    <!--right slidebar-->
    <script src="js/slidebars.min.js"></script>