#!/bin/bash

rm ../data/out/*.png

cd ../data/$1/tmp

test=0
for i in 0 1 2 3 4 5 6 7 8 9; do
	for j in 0 1 2 3 4 5 6 7 8 9; do
		for k in 0 1 2 3 4 5 6 7 8 9; do
			rm *.png
			pattern=0$i$j$k?.png
			cp ../images/$pattern .
			if [ $? = "1" ]; then
				test=1;
				break;
			fi
			gimp --verbose -i -d -f -b '(remove-background "*.png" '$2' '$3')' -b '(gimp-quit 0)' > tttt 2>&1
			sleep .1
		done
		if [ $test = "1" ]; then break; fi
	done
	if [ $test = "1" ]; then break; fi
done