<div style='display: block; font-size: 0px;'>

<div class='footer1'>
<div class='col-4 col-m-12' style='padding: 0px; margin: 0px; font-size: 14px; text-align: left;'>
<h3>ABOUT US</h3>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</div>
<div class='col-4 col-m-12' style='padding: 0px; margin: 0px; font-size: 14px; text-align: left;'>
<h3>QUICK LINKS</h3>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</div>
<div class='col-4 col-m-12' style='padding: 0px; margin: 0px; font-size: 14px; text-align: left;'>
<h3>GET IN TOUCH</h3>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</div>
</div>
<div class='footer2'>
<div class='col-8 col-m-12' style='padding: 20px; margin: 0px; text-align: left; font-size: 12px;'>
&copy;CasterBuddy 2016 | All rights reserved
</div>
<div class='col-4 col-m-12' style='padding: 0px; margin: 0px;'>
<img src='images/social.png'>
</div>
<div style="clear: both;"></div>
</div>

</div>

    <!-- js placed at the end of the document so the pages load faster -->
